### ISSUE TITLE
ansible_lint.yml ignores  `args: "-c .ansible-lint"`

### ISSUE THREAD

**Issue by robin-checkmk** [ansible/ansible-content-actions#15]
It is probably just a stupid oversight, but I am trying to infuse my custom `.ansible-lint` configuration into the follows as seen below. But the action seems to ignore this option, even though I can see the argument is passed to the command. Can anyone tell, what I am missing here?

```yaml
  ansible-lint:
    uses: ansible/ansible-content-actions/.github/workflows/ansible_lint.yaml@main
    with:
      args: "-c .ansible-lint"
```
